package profile

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/ethanhq/cc-fleet/internal/config"
)

// sampleProvider returns a representative *config.Provider used across tests.
func sampleProvider() *config.Provider {
	return &config.Provider{
		Name:           "deepseek",
		BaseURL:        "https://api.deepseek.com/anthropic",
		DefaultModel:   "deepseek-v4-flash",
		ModelsEndpoint: "https://api.deepseek.com/v1/models",
		SecretBackend:  "file",
		SecretRef:      "deepseek.key",
		Enabled:        true,
		AddedAt:        time.Date(2026, 5, 24, 0, 0, 0, 0, time.UTC),
	}
}

// isolateHome points $HOME at a temp dir so ProfilesDir() is sandboxed.
func isolateHome(t *testing.T) string {
	t.Helper()
	home := t.TempDir()
	t.Setenv("HOME", home)
	return home
}

func TestGenerateForProvider_Snapshot(t *testing.T) {
	v := sampleProvider()
	const helper = "/usr/local/bin/cc-fleet"
	// A single-model provider (no strong/fast/effort): every Claude Code model tier
	// is pinned to the default so no built-in claude-* id can escape to the provider.
	const want = `{
  "apiKeyHelper": "/usr/local/bin/cc-fleet keyget deepseek",
  "env": {
    "ANTHROPIC_BASE_URL": "https://api.deepseek.com/anthropic",
    "ANTHROPIC_DEFAULT_HAIKU_MODEL": "deepseek-v4-flash",
    "ANTHROPIC_DEFAULT_OPUS_MODEL": "deepseek-v4-flash",
    "ANTHROPIC_DEFAULT_SONNET_MODEL": "deepseek-v4-flash",
    "CLAUDE_CODE_SUBAGENT_MODEL": "deepseek-v4-flash"
  }
}`

	got, err := GenerateForProvider(v, helper)
	if err != nil {
		t.Fatalf("GenerateForProvider: %v", err)
	}
	if strings.TrimSpace(string(got)) != strings.TrimSpace(want) {
		t.Fatalf("snapshot mismatch:\n--- got ---\n%s\n--- want ---\n%s\n", got, want)
	}

	// Reverse: produced bytes must parse as JSON and round-trip both fields.
	var back struct {
		APIKeyHelper string            `json:"apiKeyHelper"`
		Env          map[string]string `json:"env"`
	}
	if err := json.Unmarshal(got, &back); err != nil {
		t.Fatalf("Unmarshal generated bytes: %v", err)
	}
	if back.APIKeyHelper != helper+" keyget deepseek" {
		t.Fatalf("apiKeyHelper = %q, want %q", back.APIKeyHelper, helper+" keyget deepseek")
	}
	if back.Env["ANTHROPIC_BASE_URL"] != v.BaseURL {
		t.Fatalf("env[ANTHROPIC_BASE_URL] = %q, want %q",
			back.Env["ANTHROPIC_BASE_URL"], v.BaseURL)
	}
}

// TestGenerateForProvider_TiersEffortAndStrip1M covers a provider that sets a strong
// and fast slot, a 1M-marked default model, and a non-max effort: the tier env
// must map opus→strong, sonnet→default, haiku/subagent→fast with the [1m] marker
// STRIPPED from every tier value, and a non-max effort must ride the settings
// effortLevel field (not the env).
func TestGenerateForProvider_TiersEffortAndStrip1M(t *testing.T) {
	v := &config.Provider{
		Name:           "deepseek",
		BaseURL:        "https://api.deepseek.com/anthropic",
		DefaultModel:   "deepseek-v4-pro[1m]",
		StrongModel:    "deepseek-v4-max[1m]",
		FastModel:      "deepseek-v4-flash",
		Effort:         "high",
		ModelsEndpoint: "https://api.deepseek.com/v1/models",
		SecretBackend:  "file",
		SecretRef:      "deepseek.key",
		Enabled:        true,
	}
	got, err := GenerateForProvider(v, "/usr/local/bin/cc-fleet")
	if err != nil {
		t.Fatalf("GenerateForProvider: %v", err)
	}
	var back struct {
		Env         map[string]string `json:"env"`
		EffortLevel string            `json:"effortLevel"`
	}
	if err := json.Unmarshal(got, &back); err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}
	want := map[string]string{
		"ANTHROPIC_DEFAULT_OPUS_MODEL":   "deepseek-v4-max", // strong, [1m] stripped
		"ANTHROPIC_DEFAULT_SONNET_MODEL": "deepseek-v4-pro", // default, [1m] stripped
		"ANTHROPIC_DEFAULT_HAIKU_MODEL":  "deepseek-v4-flash",
		"CLAUDE_CODE_SUBAGENT_MODEL":     "deepseek-v4-pro", // default
	}
	for k, w := range want {
		if back.Env[k] != w {
			t.Errorf("env[%s] = %q, want %q", k, back.Env[k], w)
		}
	}
	if _, ok := back.Env["CLAUDE_CODE_EFFORT_LEVEL"]; ok {
		t.Errorf("a non-max effort must NOT set CLAUDE_CODE_EFFORT_LEVEL env, got %q", back.Env["CLAUDE_CODE_EFFORT_LEVEL"])
	}
	if back.EffortLevel != "high" {
		t.Errorf("effortLevel = %q, want high", back.EffortLevel)
	}
}

// TestGenerateForProvider_MaxEffortRidesEnv covers effort=max: it must ride the env
// (the only knob that expresses max) and NOT the settings effortLevel field.
func TestGenerateForProvider_MaxEffortRidesEnv(t *testing.T) {
	v := sampleProvider()
	v.Effort = "max"
	got, err := GenerateForProvider(v, "/usr/local/bin/cc-fleet")
	if err != nil {
		t.Fatalf("GenerateForProvider: %v", err)
	}
	var back struct {
		Env         map[string]string `json:"env"`
		EffortLevel string            `json:"effortLevel"`
	}
	if err := json.Unmarshal(got, &back); err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}
	if back.Env["CLAUDE_CODE_EFFORT_LEVEL"] != "max" {
		t.Errorf("env CLAUDE_CODE_EFFORT_LEVEL = %q, want max", back.Env["CLAUDE_CODE_EFFORT_LEVEL"])
	}
	if back.EffortLevel != "" {
		t.Errorf("max effort must NOT set the settings effortLevel field, got %q", back.EffortLevel)
	}
}

func TestGenerateForProvider_RejectsBadInputs(t *testing.T) {
	cases := []struct {
		name   string
		v      *config.Provider
		helper string
	}{
		{"nil provider", nil, "/abs/cc-fleet"},
		{"empty name", &config.Provider{BaseURL: "https://x"}, "/abs/cc-fleet"},
		{"empty base_url", &config.Provider{Name: "x"}, "/abs/cc-fleet"},
		{"empty helper", sampleProvider(), ""},
		{"relative helper", sampleProvider(), "cc-fleet"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := GenerateForProvider(tc.v, tc.helper); err == nil {
				t.Fatalf("GenerateForProvider(%+v, %q): want error, got nil", tc.v, tc.helper)
			}
		})
	}
}

func TestWriteForProvider_FilePerm(t *testing.T) {
	isolateHome(t)
	v := sampleProvider()

	path, err := WriteForProvider(v, "/usr/local/bin/cc-fleet")
	if err != nil {
		t.Fatalf("WriteForProvider: %v", err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("Stat: %v", err)
	}
	if got := info.Mode().Perm(); got != 0o600 {
		t.Fatalf("profile mode = %o, want 0600", got)
	}

	// Content sanity: matches GenerateForProvider output byte-for-byte.
	gotBytes, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	wantBytes, err := GenerateForProvider(v, "/usr/local/bin/cc-fleet")
	if err != nil {
		t.Fatalf("GenerateForProvider: %v", err)
	}
	if string(gotBytes) != string(wantBytes) {
		t.Fatalf("file content mismatch:\n--- file ---\n%s\n--- want ---\n%s\n",
			gotBytes, wantBytes)
	}
}

func TestWriteForProvider_Atomic_NoTempLeft(t *testing.T) {
	isolateHome(t)
	v := sampleProvider()

	if _, err := WriteForProvider(v, "/usr/local/bin/cc-fleet"); err != nil {
		t.Fatalf("WriteForProvider: %v", err)
	}
	dir, err := ProfilesDir()
	if err != nil {
		t.Fatalf("ProfilesDir: %v", err)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}

	var leaked []string
	for _, e := range entries {
		// CreateTemp inserts a random suffix between our prefix and ".tmp" —
		// the final 4 chars are always ".tmp" when our temp leaks.
		if strings.HasSuffix(e.Name(), ".tmp") {
			leaked = append(leaked, e.Name())
		}
	}
	if len(leaked) > 0 {
		t.Fatalf("temp files leaked: %v", leaked)
	}

	// And the real file is present.
	wantName := v.Name + ".json"
	var found bool
	for _, e := range entries {
		if e.Name() == wantName {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("expected %s in %s; got entries %v", wantName, dir, entries)
	}
}

func TestWriteForProvider_HelperBinaryEmpty_UsesExecutable(t *testing.T) {
	isolateHome(t)
	v := sampleProvider()

	exe, err := os.Executable()
	if err != nil {
		t.Fatalf("os.Executable: %v", err)
	}

	path, err := WriteForProvider(v, "")
	if err != nil {
		t.Fatalf("WriteForProvider: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	var back struct {
		APIKeyHelper string `json:"apiKeyHelper"`
	}
	if err := json.Unmarshal(data, &back); err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}
	want := exe + " keyget " + v.Name
	if back.APIKeyHelper != want {
		t.Fatalf("apiKeyHelper = %q, want %q", back.APIKeyHelper, want)
	}
}

func TestWriteForProvider_OverwriteExisting(t *testing.T) {
	isolateHome(t)
	v := sampleProvider()

	// First write.
	if _, err := WriteForProvider(v, "/old/path/cc-fleet"); err != nil {
		t.Fatalf("first WriteForProvider: %v", err)
	}
	// Second write with a different helper path so we can prove the file
	// content actually changed.
	path, err := WriteForProvider(v, "/new/path/cc-fleet")
	if err != nil {
		t.Fatalf("second WriteForProvider: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !strings.Contains(string(data), "/new/path/cc-fleet keyget deepseek") {
		t.Fatalf("expected new helper path in file; got:\n%s", data)
	}
	if strings.Contains(string(data), "/old/path/cc-fleet") {
		t.Fatalf("old helper path leaked into rewritten file:\n%s", data)
	}
}

func TestRemoveForProvider_OK(t *testing.T) {
	isolateHome(t)
	v := sampleProvider()

	path, err := WriteForProvider(v, "/usr/local/bin/cc-fleet")
	if err != nil {
		t.Fatalf("WriteForProvider: %v", err)
	}
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("Stat before remove: %v", err)
	}
	if err := RemoveForProvider(v.Name); err != nil {
		t.Fatalf("RemoveForProvider: %v", err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("expected file gone, got Stat err=%v", err)
	}
}

func TestRemoveForProvider_MissingNotError(t *testing.T) {
	isolateHome(t)
	if err := RemoveForProvider("never-existed"); err != nil {
		t.Fatalf("RemoveForProvider on missing: want nil, got %v", err)
	}
}

func TestProfilePath(t *testing.T) {
	home := isolateHome(t)
	got, err := ProfilePath("deepseek")
	if err != nil {
		t.Fatalf("ProfilePath: %v", err)
	}
	want := filepath.Join(home, ".claude", "profiles", "deepseek.json")
	if got != want {
		t.Fatalf("ProfilePath = %q, want %q", got, want)
	}
}

func TestProfilePath_EmptyProvider(t *testing.T) {
	isolateHome(t)
	if _, err := ProfilePath(""); err == nil {
		t.Fatalf("ProfilePath(\"\"): want error, got nil")
	}
}

func TestProfilesDir_NoHome(t *testing.T) {
	t.Setenv("HOME", "")
	if _, err := ProfilesDir(); err == nil {
		t.Fatalf("ProfilesDir: want error when HOME unset, got nil")
	}
}
